"""Flask backend for the tomato disease detector."""

from __future__ import annotations

from datetime import datetime
from pathlib import Path
import sys

PROJECT_ROOT = Path(__file__).resolve().parent.parent

if str(PROJECT_ROOT) not in sys.path:
    sys.path.insert(0, str(PROJECT_ROOT))

from flask import (
    Flask,
    jsonify,
    request,
    send_from_directory,
)
from werkzeug.utils import secure_filename

try:
    from backend.database import (
        get_connection,
        init_db,
    )
except ModuleNotFoundError:
    from database import (
        get_connection,
        init_db,
    )

from src.inference.tflite_predict import (
    predict_tflite_image,
)
from src.utils.config import (
    CAPTURED_IMAGES_DIR,
    MODEL_PATH,
)


DASHBOARD_DIR = PROJECT_ROOT / "dashboard"

app = Flask(
    __name__,
    static_folder=str(
        PROJECT_ROOT / "backend" / "static"
    ),
)


ALLOWED_IMAGE_EXTENSIONS = {
    ".jpg",
    ".jpeg",
    ".png",
    ".webp",
    ".bmp",
}


ALLOWED_PREDICTIONS = {
    "Bacterial_spot",
    "Early_blight",
    "Late_blight",
    "Leaf_Mold",
    "Septoria_leaf_spot",
    "Spider_mites Two-spotted_spider_mite",
    "Target_Spot",
    "Tomato_Yellow_Leaf_Curl_Virus",
    "Tomato_mosaic_virus",
    "healthy",
    "powdery_mildew",
}


def validate_prediction_payload(
    prediction,
    confidence,
    device_id,
):
    """Validate a device prediction request."""

    if (
        not prediction
        or confidence is None
        or not device_id
    ):
        return (
            "prediction, confidence, and "
            "device_id are required."
        )

    if prediction not in ALLOWED_PREDICTIONS:
        return (
            f"Invalid prediction label: "
            f"{prediction}"
        )

    try:
        confidence_value = float(
            confidence
        )
    except (
        TypeError,
        ValueError,
    ):
        return (
            "confidence must be a numeric value."
        )

    if not 0.0 <= confidence_value <= 1.0:
        return (
            "confidence must be between 0 and 1."
        )

    return None


@app.get("/")
@app.get("/dashboard")
def dashboard_index():
    """Serve the dashboard."""

    return send_from_directory(
        str(DASHBOARD_DIR),
        "index.html",
    )


@app.get("/dashboard/<path:filename>")
def dashboard_static(filename: str):
    """Serve dashboard static files."""

    return send_from_directory(
        str(DASHBOARD_DIR),
        filename,
    )


@app.get("/captured-images/<path:filename>")
def captured_image(filename: str):
    """Serve captured images."""

    return send_from_directory(
        str(CAPTURED_IMAGES_DIR),
        filename,
    )


@app.before_request
def ensure_db() -> None:
    """Ensure database tables exist."""

    init_db()


@app.get("/api/health")
def health():
    """Health-check endpoint."""

    return jsonify(
        {
            "status": "ok",
            "message": (
                "Tomato disease detector "
                "backend is running."
            ),
        }
    ), 200


@app.post("/api/predictions")
def create_prediction():
    """
    Receive a prediction generated by a device.
    """

    payload = (
        request.get_json(
            silent=True
        )
        or {}
    )

    prediction = payload.get(
        "prediction"
    )

    confidence = payload.get(
        "confidence"
    )

    device_id = payload.get(
        "device_id"
    )

    image_path = payload.get(
        "image_path"
    )

    timestamp = (
        payload.get("timestamp")
        or datetime.utcnow().isoformat()
    )

    validation_error = (
        validate_prediction_payload(
            prediction,
            confidence,
            device_id,
        )
    )

    if validation_error:
        return jsonify(
            {"error": validation_error}
        ), 400

    confidence_value = float(
        confidence
    )

    connection = get_connection()

    try:
        cursor = connection.execute(
            """
            INSERT INTO predictions
            (
                prediction,
                confidence,
                device_id,
                timestamp,
                image_path
            )
            VALUES (?, ?, ?, ?, ?)
            """,
            (
                prediction,
                confidence_value,
                device_id,
                timestamp,
                image_path,
            ),
        )

        connection.commit()

        prediction_id = cursor.lastrowid

    finally:
        connection.close()

    return jsonify(
        {
            "id": prediction_id,
            "prediction": prediction,
            "confidence": confidence_value,
            "device_id": device_id,
            "timestamp": timestamp,
            "image_path": image_path,
        }
    ), 201


@app.post("/api/predict-image")
def predict_uploaded_image():
    """
    Receive an image, run TFLite inference,
    and store the prediction.
    """

    image = request.files.get(
        "image"
    )

    if image is None or not image.filename:
        return jsonify(
            {
                "error": (
                    "An image file is required."
                )
            }
        ), 400

    filename = secure_filename(
        image.filename
    )

    if not filename:
        return jsonify(
            {
                "error": (
                    "The image filename "
                    "is invalid."
                )
            }
        ), 400

    extension = Path(
        filename
    ).suffix.lower()

    if extension not in ALLOWED_IMAGE_EXTENSIONS:
        return jsonify(
            {
                "error": (
                    "Please upload a JPG, PNG, "
                    "WebP, or BMP image."
                )
            }
        ), 400

    CAPTURED_IMAGES_DIR.mkdir(
        parents=True,
        exist_ok=True,
    )

    saved_path = (
        CAPTURED_IMAGES_DIR
        / (
            f"{datetime.utcnow().strftime('%Y%m%d_%H%M%S_%f')}"
            f"_{filename}"
        )
    )

    image.save(saved_path)

    try:
        result = predict_tflite_image(
            model_path=MODEL_PATH,
            image_path=saved_path,
        )

    except (
        FileNotFoundError,
        ValueError,
        OSError,
    ) as exc:

        saved_path.unlink(
            missing_ok=True
        )

        return jsonify(
            {"error": str(exc)}
        ), 400

    device_id = request.form.get(
        "device_id",
        "dashboard-camera",
    )

    timestamp = (
        datetime.utcnow().isoformat()
    )

    connection = get_connection()

    try:
        cursor = connection.execute(
            """
            INSERT INTO predictions
            (
                prediction,
                confidence,
                device_id,
                timestamp,
                image_path
            )
            VALUES (?, ?, ?, ?, ?)
            """,
            (
                result["prediction"],
                result["confidence"],
                device_id,
                timestamp,
                saved_path.name,
            ),
        )

        connection.commit()

        prediction_id = cursor.lastrowid

    finally:
        connection.close()

    return jsonify(
        {
            "id": prediction_id,
            "prediction": result[
                "prediction"
            ],
            "label": result["label"],
            "disease": result["disease"],
            "confidence": result[
                "confidence"
            ],
            "confidence_status": result[
                "confidence_status"
            ],
            "threshold": result[
                "threshold"
            ],
            "device_id": device_id,
            "timestamp": timestamp,
            "image_path": saved_path.name,
            "image_url": (
                f"/captured-images/"
                f"{saved_path.name}"
            ),
        }
    ), 201


@app.get("/api/predictions")
def list_predictions():
    """Return prediction history."""

    connection = get_connection()

    try:
        rows = connection.execute(
            """
            SELECT
                id,
                prediction,
                confidence,
                device_id,
                timestamp,
                image_path
            FROM predictions
            ORDER BY id DESC
            """
        ).fetchall()

    finally:
        connection.close()

    return jsonify(
        [
            {
                "id": row["id"],
                "prediction": row[
                    "prediction"
                ],
                "confidence": row[
                    "confidence"
                ],
                "device_id": row[
                    "device_id"
                ],
                "timestamp": row[
                    "timestamp"
                ],
                "image_path": row[
                    "image_path"
                ],
            }
            for row in rows
        ]
    ), 200


@app.get("/api/latest")
def latest_prediction():
    """Return the most recent prediction."""

    connection = get_connection()

    try:
        row = connection.execute(
            """
            SELECT
                id,
                prediction,
                confidence,
                device_id,
                timestamp,
                image_path
            FROM predictions
            ORDER BY id DESC
            LIMIT 1
            """
        ).fetchone()

    finally:
        connection.close()

    if row is None:
        return jsonify(
            {
                "message": (
                    "No predictions "
                    "available yet."
                )
            }
        ), 404

    return jsonify(
        {
            "id": row["id"],
            "prediction": row[
                "prediction"
            ],
            "confidence": row[
                "confidence"
            ],
            "device_id": row[
                "device_id"
            ],
            "timestamp": row[
                "timestamp"
            ],
            "image_path": row[
                "image_path"
            ],
        }
    ), 200


if __name__ == "__main__":
    app.run(
        host="0.0.0.0",
        port=8000,
        debug=True,
    )